# Generated by Django 5.2.18 on 2026-10-08 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('job_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('source_base_url', models.URLField()),
                ('request_url', models.TextField()),
                ('poll_url', models.TextField(blank=True)),
                ('since', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='in_progress', max_length=16)),
                ('transaction_time', models.CharField(blank=True, max_length=64, null=True)),
                ('expected_counts', models.JSONField(blank=True, null=True)),
                ('manifest_json', models.JSONField(blank=True, null=True)),
                ('kicked_off_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=32)),
                ('url', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('line_count', models.PositiveIntegerField(blank=True, null=True)),
                ('inserted_count', models.PositiveIntegerField(blank=True, null=True)),
                ('duplicate_count', models.PositiveIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='pipeline.exportjob')),
            ],
        ),
        migrations.CreateModel(
            name='RawResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=32)),
                ('source_id', models.CharField(max_length=128)),
                ('version_id', models.CharField(max_length=128)),
                ('last_updated', models.CharField(blank=True, max_length=64)),
                ('payload', models.TextField()),
                ('payload_sha256', models.CharField(max_length=64)),
                ('line_no', models.PositiveIntegerField()),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='pipeline.exportfile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='exportfile',
            constraint=models.UniqueConstraint(fields=('job', 'url'), name='unique_file_per_job'),
        ),
        migrations.AddIndex(
            model_name='rawresource',
            index=models.Index(fields=['resource_type', 'source_id'], name='pipeline_ra_resourc_ae63e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawresource',
            constraint=models.UniqueConstraint(fields=('resource_type', 'source_id', 'version_id'), name='unique_resource_version'),
        ),
    ]
