# Generated by Django 5.2.18 on 2026-10-08 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=32)),
                ('source_id', models.CharField(max_length=128)),
                ('reason', models.CharField(max_length=255)),
                ('mapping_version', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.rawresource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('resource_type', 'source_id'), name='unique_quarantined_resource')],
            },
        ),
    ]
