# Generated by Django 5.2.18 on 2026-10-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_quarantine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawresource',
            name='line_no',
            field=models.PositiveIntegerField(help_text='1-based line number inside the NDJSON file; with file, traces the row to its exact source line.'),
        ),
        migrations.AlterField(
            model_name='rawresource',
            name='payload_sha256',
            field=models.CharField(help_text='SHA-256 of the exact NDJSON line; detects changed content and serves as version_id when the source has no meta.versionId.', max_length=64),
        ),
    ]
