# Generated by Django 5.2.18 on 2026-10-08 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_raw_resource_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passed', models.BooleanField()),
                ('checks', models.JSONField(help_text='One entry per validation check: name, expected, actual, passed, detail.')),
                ('totals', models.JSONField(help_text='Counts per type, quarantine reasons and duplicate candidates.')),
                ('sample', models.JSONField(help_text='Sample size, seed and field-level mismatches found.')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='pipeline.exportjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
