# Generated by Django 5.2.18 on 2026-10-08 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(max_length=255)),
                ('source_id', models.CharField(max_length=128)),
                ('source_version', models.CharField(max_length=128)),
                ('source_last_updated', models.DateTimeField(null=True)),
                ('given_name', models.CharField(blank=True, max_length=255)),
                ('family_name', models.CharField(blank=True, max_length=255)),
                ('birth_date', models.CharField(blank=True, max_length=10)),
                ('birth_date_precision', models.CharField(blank=True, max_length=5)),
                ('gender', models.CharField(max_length=16, null=True)),
                ('deceased', models.BooleanField(null=True)),
                ('deceased_at', models.DateTimeField(null=True)),
                ('mapping_version', models.CharField(max_length=16)),
                ('migrated_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['family_name', 'given_name'], name='clinical_pa_family__524d56_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'source_id'), name='unique_patient_source')],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(max_length=255)),
                ('source_id', models.CharField(max_length=128)),
                ('source_version', models.CharField(max_length=128)),
                ('source_last_updated', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=32, null=True)),
                ('category', models.CharField(max_length=64, null=True)),
                ('code_system', models.TextField(blank=True)),
                ('code', models.CharField(blank=True, max_length=128)),
                ('code_display', models.TextField(blank=True)),
                ('code_text', models.TextField(blank=True)),
                ('value_type', models.CharField(max_length=32)),
                ('value_num', models.DecimalField(decimal_places=10, max_digits=30, null=True)),
                ('value_unit', models.CharField(blank=True, max_length=64)),
                ('value_text', models.TextField(blank=True)),
                ('data_absent_reason', models.CharField(blank=True, max_length=64)),
                ('effective_start', models.DateTimeField(null=True)),
                ('effective_end', models.DateTimeField(null=True)),
                ('effective_precision', models.CharField(blank=True, max_length=8)),
                ('components_json', models.JSONField(null=True)),
                ('mapping_version', models.CharField(max_length=16)),
                ('migrated_at', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='clinical.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'effective_start'], name='clinical_ob_patient_d1ffc9_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'source_id'), name='unique_observation_source')],
            },
        ),
        migrations.CreateModel(
            name='PatientDuplicateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_reason', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('patient_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clinical.patient')),
                ('patient_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='clinical.patient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('patient_a', 'patient_b', 'match_reason'), name='unique_duplicate_pair')],
            },
        ),
        migrations.CreateModel(
            name='PatientIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.TextField(blank=True)),
                ('value', models.CharField(max_length=255)),
                ('type_code', models.CharField(blank=True, max_length=64)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='clinical.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['system', 'value'], name='clinical_pa_system_5f245e_idx')],
            },
        ),
    ]
