# Generated by Django 5.2.18 on 2026-10-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='value_num',
            field=models.DecimalField(decimal_places=10, help_text='Numeric copy for sorting and filtering; SQLite keeps ~15 significant digits.', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='value_text',
            field=models.TextField(blank=True, help_text='Value exactly as received (numbers keep full precision); use this for display.'),
        ),
    ]
