# Generated by Django 5.2.18 on 2026-10-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_observation_value_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='deceased_precision',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
